version = 1

[[apps]]
command = "node --run start"
cwd = "/root/telegram-youtube-bot"
health_cmd = "curl -fsS --head http://localhost:4444/healthcheck"
name = "telegram-youtube-bot"
wait_ready = true
