name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
      - run: bun ci
      - parallel:
          - run: bun dedupe --check
          - run: bunx eslint
          - run: bunx tsc
          - run: bun run test
          - run: bun run build
      - uses: actions/upload-artifact@v7
        with:
          name: artifacts
          path: |
            cli
            oxfile.toml

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: artifacts
      - uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "cli,oxfile.toml"
          target: ${{ secrets.APP_DIR }}
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd ${{ secrets.APP_DIR }}
            echo '${{ secrets.ENV_FILE }}' > .env
            chmod +x cli
            oxmgr validate ./oxfile.toml
            oxmgr apply ./oxfile.toml
            oxmgr restart telegram-youtube-bot
